/*
 The code in this file was generated by running tools::package_native_routine_registration_skeleton(".")
 as suggested in
 https://stackoverflow.com/questions/42313373/r-cmd-check-note-found-no-calls-to-r-registerroutines-r-usedynamicsymbols
 */

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* FIXME:
 Check these declarations against the C/Fortran source code.
 */

/* .C calls */
extern void compute_yhat_zz_R(void *, void *, void *, void *, void *, void *, void *, void *, void *);
extern void ComputeInteractionsWithIndices(void *, void *, void *, void *, void *, void *);
extern void ggdescent_logistic_R(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);

/* .Call calls */
extern SEXP _CRTConjoint_demean_center(SEXP, SEXP, SEXP, SEXP);
extern SEXP _CRTConjoint_fast_demean(SEXP, SEXP, SEXP);

static const R_CMethodDef CEntries[] = {
  {"compute_yhat_zz_R",              (DL_FUNC) &compute_yhat_zz_R,               9},
  {"ComputeInteractionsWithIndices", (DL_FUNC) &ComputeInteractionsWithIndices,  6},
  {"ggdescent_logistic_R",           (DL_FUNC) &ggdescent_logistic_R,           24},
  {NULL, NULL, 0}
};

static const R_CallMethodDef CallEntries[] = {
  {"_CRTConjoint_demean_center", (DL_FUNC) &_CRTConjoint_demean_center, 4},
  {"_CRTConjoint_fast_demean",   (DL_FUNC) &_CRTConjoint_fast_demean,   3},
  {NULL, NULL, 0}
};

void R_init_CRTConjoint(DllInfo *dll)
{
  R_registerRoutines(dll, CEntries, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
