# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

demean_center <- function(zz, rows, cols, m) {
    .Call('_CRTConjoint_demean_center', PACKAGE = 'CRTConjoint', zz, rows, cols, m)
}

fast_demean <- function(zz, rows, cols) {
    .Call('_CRTConjoint_fast_demean', PACKAGE = 'CRTConjoint', zz, rows, cols)
}

